### ISSUE TITLE
SuperSourceBorderEnable makes a macro invalid

### ISSUE THREAD

**Issue by Lange** [LibAtem/AtemMacroEditor#3]
Adding a `SuperSourceBorderEnable` command to a macro via AtemMacroEditor results in the macro somehow becoming invalid. It displays a warning icon in the ATEM software, and cannot be exported. It will be completely omitted from the export XML by the first-party ATEM Software Control program.

![image](https://user-images.githubusercontent.com/873012/43600999-c070d5ae-9651-11e8-8d75-57cf3c85b35f.png)

It does not seem to matter what value is used for `SuperSourceBorderEnable`. All values exhibit this behavior.

**Comment by Julusian** [comment]
I don't think I ever got around to testing the supersource macro ops against an atem, all the supersource ones should be good now and even have a unit test :)
Both this and #4 should be fixed now https://drive.google.com/open?id=1lWANr7VjLdj6MJhqdlR-VJipNmmLK6Vp

**Comment by Lange** [comment]
Yep, this one is confirmed fixed.
